### PR TITLE
Extend capability of standings.py

### PR DESCRIPTION
**Pull request by kunalcsc630**
Added ability to pull standings up to 1903 instead of up to 1969. Working on extending ability all the way to 1871.

### CODE REVIEW

**Comment by jldbc** [comment]
Love the idea here. I'm guessing this is meant to return league-level standings for seasons before 1969? 

Running locally I get an error: 
```
from standings import standings
test = standings(1944)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jledoux/Documents/projects/pybaseball/pybaseball/standings.py", line 71, in standings
    tables = get_tables(code, season)
  File "/Users/jledoux/Documents/projects/pybaseball/pybaseball/standings.py", line 31, in get_tables
    headings = [th.get_text() for th in table.find("tr").find_all("th")]
UnboundLocalError: local variable 'table' referenced before assignment
```

**Comment by kunalcsc630** [comment]
Yep. This is bizarre because when I run it locally, it works perfectly fine. I've added one statement. Maybe that's why you're getting errors?
screen shot 2018-02-02 at 9 09 36 am
screen shot 2018-02-02 at 9 10 14 am
screen shot 2018-02-02 at 9 10 30 am

**Comment by jldbc** [comment]
Still getting the same error on my end. It looks like the issue is coming from line 31:
`headings = [th.get_text() for th in table.find("tr").find_all("th")]`

`table` isn't yet defined here (it isn't passed from `standings` to `get_tables`, so setting it before calling the function on line 64 won't help). 

For post-1969 `table` exists in `headings = [th.get_text() for th in table.find("tr").find_all("th")]` because it's within the loop `for table in tables:`. I think changing the name of line 30's variable from `tables` to `table` solves this, since pre-1969 isn't iterating through a list of tables the way its post-1969 counterpart is.

**Comment by kunalcsc630** [comment]
Ah yes! I now notice that in my screenshot, I use the variable `tables` but on GitHub, the variable is `table`. I believe that should fix the issue. Does it work for you now?

**Comment by kunalcsc630** [comment]
Just extended capability to standings from 1871 onwards, the earliest possible year from which you can pull standings.

**Comment by jldbc** [comment]
Your fix to the previous problem works now, but pre-1903 queries error out for the same reason as before: 

UnboundLocalError: local variable 'tables' referenced before assignment

Did you mean to change line 71 to `else:` instead of `elif season>=1903:` so that a pre-1903 query is processed by the block of code within that else statement? Otherwise, `tables` won't exist on line 77 if `season` < 1903.

Once this is fixed these changes should be ready to merge.

**Comment by kunalcsc630** [comment]
Yeah. Hopefully everything else works after that fix.

**Comment by jldbc** [comment]
Looks good now. Thanks!

**Pull request merged**
