### PR TITLE
Add a matrix to test on all python versions

### PR DESCRIPTION
**Pull request by TheCleric**
Testing out a matrix that will test changes against all current python versions.

@schorrm I think this could help catch things like what I found in #231 which was a TypeError that seems to happen in 3.7+, but not previously caught in our 3.6 tests (which you can see are causing failures below in 3.7 and 3.8).

As well we may be able to easily add 3.10 when that's ready to see how our code base will fair.

### CODE REVIEW

**Comment by schorrm** [comment]
I would prefer to not commit to supporting so many in the tests, it also has time costs

**Comment by TheCleric** [comment]
> I would prefer to not commit to supporting so many in the tests, it also has time costs

They run in parallel, so the time cost should be minimal.

**Comment by schorrm** [comment]
red exs scary

**Comment by TheCleric** [comment]
> red exs scary

They'll get fixed after the other PR gets merged (and master gets merged in here)

**Comment by schorrm** [comment]
Other merged, can you merge back and appease the CI?

**Comment by TheCleric** [comment]
@schorrm all tests passing now in case you didn't see it.

**Pull request merged**
