### PR TITLE
Add team ids and player ids; team id mapper for Fangraphs

### PR DESCRIPTION
**Pull request by TheCleric**
Team ID Lookup - Fangraphs

`fangraphs_teams(season: int, league: str) -> pd.DataFrame`

Return a mapping dataframe to map Fangraphs' team id to Lahman data. This can then be used to map to BRef and Retrosheet data with Lahman's `teamIDBR` and `teamIDretro` columns.

### CODE REVIEW

**Comment by TheCleric** [comment]
This (along with #128) will resolve the lingering issues I originally brought up in #85

**Comment by schorrm** [comment]
I feel like I'm missing something here

**Comment by TheCleric** [comment]
Right now we don't have an easy way to join Fangraphs data to other data sources for two reasons:
1) We don't actually return the Fangraphs id (either player or team) in any of our results
2) We had no way previously to join Fangraphs team data to other team data.

This PR solves both of those problems.

**Comment by schorrm** [comment]
We had the team name, but I hear that. I thought FGID was in the player frames?

**Comment by schorrm** [comment]
Is TeamIDFG just a number? Is it a constant one (I imagine it is)?
Can we just have a map of name:number and apply those?

**Comment by TheCleric** [comment]
> Is TeamIDFG just a number? Is it a constant one (I imagine it is)?
> Can we just have a map of name:number and apply those?

I honestly thought about that. Actually I was thinking about storing the result of this (possibly along with the existing `first_season_map` in `utils.py`) as a CSV file that gets loaded (like `mlbstadiums.csv`) instead of hitting the actual API since this data will never change unless:

- A team gets added to the MLB
- A team gets dropped by the MLB
- A team moves cities

Let me know if you'd like to go to a local cache of this data instead. We can keep the function to regenerate if need be, but only return the cache for end users.

**Comment by schorrm** [comment]
I _think_ this data should be *so* non-volatile, it might even make sense to just straight up hardcode it in (not even the cache) and then change in a bump if there's an expansion team or a rename (I think we might expect 1-2 changes / **decade**). AFAIK, the only change we would've had to make in the 2010s was LA Angels of Anaheim to LA Angels in 2016.

**Comment by TheCleric** [comment]
> I _think_ this data should be _so_ non-volatile, it might even make sense to just straight up hardcode it in (not even the cache) and then change in a bump if there's an expansion team or a rename (I think we might expect 1-2 changes / **decade**). AFAIK, the only change we would've had to make in the 2010s was LA Angels of Anaheim to LA Angels in 2016.

To be clear, when I say a cache, I don't mean our new caching mechanism, I just mean we commit the data in the project as a CSV to keep us from having 100-200 lines of a dictionary definition.

**Comment by schorrm** [comment]
That sounds correct to me

**Comment by TheCleric** [comment]
FYI Tests are failing here due to a bug that is fixed in PR #144

**Comment by schorrm** [comment]
LGTM

**Pull request merged**
