### PR TITLE
Split Statcast Queries

### PR DESCRIPTION
**Pull request by andersonfrailey**
This PR is an implementation of the solution to issue #20 I proposed in issue #22. So far I've only implemented this change in `statcast_batter` and `statcast_pitcher`, I haven't tried anything with the rest of the `statcast` functions. I created a new `utils.py` file to avoid some code duplication.

I've run `statcast_batter` and `statcast_pitcher` a few times and everything seems to work as it should. Labeled WIP because I want to play with the other `statcast` functions to see if they have any of the same request timeout errors before saying it's ready for a full review.

### CODE REVIEW

**Comment by andersonfrailey** [comment]
Looks like the `statcast` function already has a method for breaking up queries so I'll leave it be in this PR and remove the WIP label.

**Comment by jldbc** [comment]
Sorry, lost track of this. Looks good to me though at first glance, the move to a utils file is also much needed. Is there any reason behind picking 60 days as the time interval to move by and not something larger? My guess is we could afford a larger step size which would make this run faster

**Comment by andersonfrailey** [comment]
@jldbc, I picked 60 days because I found that once I started trying queries for time intervals larger than about 2 months the requests would time out. I can experiment a little and see if there are slightly larger intervals I could use.

**Comment by jldbc** [comment]
Are you using the bugfix from 6d0952c51bc3f00a4ff54b6a137a0b82eafe2d75? The size of these requests is a lot smaller now that it's filtering for players instead of returning everything. I got it to work with 365+ days as the interval. Let me know what you find after testing it some and I'll merge whatever's working best.

**Comment by andersonfrailey** [comment]
@jldbc, I tested it out a bit after the bug fix you pointed out and could run queries up to six years before running into a timeout issue. I'll update this PR accordingly.

**Comment by jldbc** [comment]
Looks good. Most players won't hit the 40k event mark on this yet since we only have this data 2008 - present, but this should future-proof this as we start to get more data

**Pull request merged**
