### PR TITLE
Fix the Fangraphs docs accuracy

### PR DESCRIPTION
**Pull request by TheCleric**

### CODE REVIEW

**Comment by TheCleric** [comment]
Broken tests on this PR came from a bad test in master. Will be fixed via #136

**Comment by schorrm** [comment]
Can you rename this something more accurate?

**Comment by TheCleric** [comment]
> Can you rename this something more accurate?

It SHOULD be accurate. I'm still getting changes sneaking in when I rebase, which is REALLY strange, as I know master has the extraneous marcels changes that are showing up here. Let me try to fix...

**Comment by TheCleric** [comment]
MUCH better!

**Comment by schorrm** [comment]
I meant rename the PR

**Comment by TheCleric** [comment]
> I meant rename the PR

I know. The PR is only about fixing the accuracy of the fangraphs.md file.

**Comment by schorrm** [comment]
Ah, ok, because the diff looked like Marcels mainly last time I looked.

**Pull request merged**
