### PR TITLE
added plot_teams function to plot all team's stats for a season(s)

### PR DESCRIPTION
**Pull request by JackMentch**
## Description

I added the function`plot_teams( )` to pybaseball/plotting.py so that you can easily plot all teams against any two variables in a dataframe

## Rationale

The two functions `team_pitching( )` and `team_batting( )` both return stats for all 30 teams. 

For example,

Running `team_batting(2023)` would return a dataframe similar to this...

| teamIDfg    | Season | Team | ... | HR | ... | BB | ... |
| ----------- | -------- | ----- | - | --- | -- | --- | -- |
|           12      | 2023     | TBR  | ... | 44 | ... | 102 | ... |
|           17      | 2023     | LAD  | ... | 30 | ... | 83 | ... |
|           30      | 2023     | CHC  | ... | 32| ... | 77 | ... |
|           34      | 2023     | TEX  | ... | 23 | ... | 89| ... |
|          ...       | ...           | ...      | ... | ...  | ... | ...    | ... |

Using my function `plot_teams( )` you could plot each team's total HRs and BBs for 2023

```python
from pybaseball import plot_teams, team_batting

data = team_batting(2023)

plot_teams(data, "HR", "BB")
```

This would generate the following plot:

plot_teams_example

## Limitations:
- Only works with dataframes generated by **team_batting** and **team_pitching**
- Adding the 30 .png files for each logo adds about 0.45 MB of storage (not sure if this is too much) 
- Only added logos for the current 30 MLB teams (if you pass a dataframe containing the Montreal Expos to plot_teams( ) it will crash since the logo does not exist)
- The function only accepts 1 dataframe. If you wanted to plot **HRs** from a team_batting dataframe and **ERA** from a team_pitching dataframe, you would have to join the two separate dataframes before passing it to plot_teams( )

### CODE REVIEW

**Review by BrayanMnz — APPROVED** [review]
LGTM, nice feature! 

The only thing is - why not adding a check for the team being passed to the function so we can check 
If the team is correctly typed instead of crashing? 

If the team doesn't exist in a MAP with all the teams available, we can just advise (Check the arguments are correctly typed, team is not available with a link to the documentation or to the map of available teams)

**Comment by JackMentch** [comment]
Hey Brayan, I'm cool with whatever you think is best! Thank you taking a look as well!

**Comment by schorrm** [comment]
This is really nice! Sorry for the delay

**Comment by schorrm** [comment]
I would suggest that we either throw an error when missing that is more informative, or can we fall back to text for missing team codes?

**Comment by JackMentch** [comment]
Hi Moshe, 

I appreciate your response! Just made a new commit that plots text (team abbreviation) instead of the logo if it cannot find a corresponding image. Let me know if this looks fine:

Screenshot 2023-05-04 at 11 01 57 AM

**Comment by schorrm** [comment]
Yeah, this is a great fallback!

**Pull request merged**
