### PR TITLE
get a logger instead of globally config logging

### LINKED ISSUE #199: global logging prevents any application to log
The Logging to file example from python docs is not working when importing pybaseball
https://docs.python.org/3/howto/logging.html#logging-from-multiple-modules
```
# myapp.py
import logging
import mylib

def main():
    logging.basicConfig(filename='myapp.log', level=logging.INFO)
    logging.info('Started')
    mylib.do_something()
    logging.info('Finished')

if __name__ == '__main__':
    main()
```

```
# mylib.py
import logging

def do_something():
    logging.info('Doing something')
```

Getting a logger from logging also doesn't work as intended

### PR DESCRIPTION
**Pull request by Maradonna90**
fixes #199

### CODE REVIEW

**Comment by schorrm** [comment]
@TheCleric can you please take a look?

**Review by TheCleric — APPROVED** [review]

**Comment by TheCleric** [comment]
> @TheCleric can you please take a look?

LGTM

**Comment by schorrm** [comment]
@Maradonna90 -- Looks good, can I just ask you to merge in the changes and push?

**Comment by Maradonna90** [comment]
failed tests seem to be cache related

**Comment by schorrm** [comment]
Yeah, those are being dealt with. LGTM, and thanks for contributing!

**Pull request merged**
