### PR TITLE
Convert batting_stats to new FG data source

### PR DESCRIPTION
**Pull request by TheCleric**

### CODE REVIEW

**Comment by schorrm** [comment]
Can you please check the behavior for null values in Integer columns? We should have a pd.NA usage there I believe (as discussed in the Pandas > 1.0 requirement).

**Comment by TheCleric** [comment]
> Can you please check the behavior for null values in Integer columns? We should have a pd.NA usage there I believe (as discussed in the Pandas > 1.0 requirement).

Added some code and test

**Comment by schorrm** [comment]
Can you please merge back updates and resolve the merge conflicts, and then this'll go through?

**Comment by TheCleric** [comment]
> Can you please merge back updates and resolve the merge conflicts, and then this'll go through?

Done! 😄

**Comment by schorrm** [comment]
Oops! I Did It Again!

**Comment by TheCleric** [comment]
Fixed. I think we are getting these conflicts because we are doing squash merges on PRs.

**Comment by schorrm** [comment]
I’ll change to the Merge commits then

**Pull request merged**
