### PR TITLE
Add BRef and Retrosheet to teamid_lookup

### PR DESCRIPTION
**Pull request by TheCleric**
In response to the request that @Am3ra made in #156, this PR adds the BRef and Retrosheet IDs to the teamid_lookup module. As well it changes the name of `fangraphs_teams` to `team_ids` (while maintaining `fangraphs_teams` as an alias for backwards compatibility.

### CODE REVIEW

**Comment by schorrm** [comment]
This looks good to me, but honestly, tiny bit worried there's no comments / controversy etc

**Comment by TheCleric** [comment]
> This looks good to me, but honestly, tiny bit worried there's no comments / controversy etc

What do you mean @schorrm ? My PRs NEVER have any comments. They just pop into existence as PERFECTION. Just look at the cache PR. 😉

**Comment by schorrm** [comment]
Lol. In general, if there's nothing, means everybody wasn't paying attn or missed something. I'll try one thing here tho: does this need a docs update?

**Comment by TheCleric** [comment]
> Lol. In general, if there's nothing, means everybody wasn't paying attn or missed something. I'll try one thing here tho: does this need a docs update?

That's actually a good point. I'll take care of that.

**Pull request merged**
